name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          -p 5432:5432
        env:
          POSTGRES_PASSWORD: 123123
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20' # Adjust to your project's Java version

      - name: Compile Code
        run: |
           javac -cp "./lib/*" src/UnitTesting.java src/LoginApp.java
      - name: Run Tests
        run: |
           cd src
           java -cp ".:../lib/*" org.junit.runner.JUnitCore UnitTesting
